#!/usr/bin/env bash 
#SBATCH -A NAISS2025-5-525      # Project
#SBATCH -p alvis                # Partition
#SBATCH -t 0-01:00:00           # time limit days-hours:minutes:seconds
#SBATCH --gpus-per-node=A40:1   # GPUs 64GB of RAM; cost factor 1.0
#SBATCH -c 8
#SBATCH --output=jobs/alvis/%x-%j.out 
#SBATCH --job-name=d3_dem

cd "$SLURM_SUBMIT_DIR" 

module purge
module load Python/3.12.3-GCCcore-13.3.0
source .venv/bin/activate

echo "Distance 3 on dem" 
srun python scripts/finetune_dem.py \
	--n_epochs 1000 \
	--batch_size 1024 \
	--dt 2 \
	--n_batches 64 \
	--lr 1e-3 \
	--min_lr 1e-5 \
	--patience 500